# Generated by Django 4.0.3 on 2022-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timescale', '0007_taskalloc_delete_taskallocadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskalloc',
            name='priority',
            field=models.CharField(default='', max_length=30),
        ),
    ]
